version: "3"
services:
  timetable:
    build: .
    depends_on:
      - postgres
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=pass123
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=timetable
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./timetable:/src/timetable
    ports:
      - "5005:80"


  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=timetable
    ports:
      - "5432:5432"

  e2e-tests:
    build:
      context: e2e_tests
    environment:
      - API_HOST=timetable
      - API_PORT=80
    volumes:
      - ./e2e_tests:/tests/